language: ruby
rvm:
  - 2.1.1
  - 2.0.0
  - 2.2.0
cache: bundler
bundler_args: --without mysql
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
notifications:
  email: false
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake test
addons:
  code_climate:
    repo_token:
      secure: "bhmBxuZbWLUyaOmq8T81xEJ+KOxF46NBbkxEMQvmlcf3r7BoODVaga0K8Rj6xVVpaMStSnFfA/KIzoxZhA1gF+/k9kK37cXnWcCljQZp9I0vYTELtdOaHakd+f+NJb+N+seNfbetjRWLLq3xd8KoIZ1AijLBq0phoTMB+/G5HEE="
