language: ruby
rvm:
  - 1.9.3
  - 2.1.1
  - 2.0.0
cache: bundler

notifications:
  email: false

addons:
  code_climate:
    repo_token:
      secure: "bhmBxuZbWLUyaOmq8T81xEJ+KOxF46NBbkxEMQvmlcf3r7BoODVaga0K8Rj6xVVpaMStSnFfA/KIzoxZhA1gF+/k9kK37cXnWcCljQZp9I0vYTELtdOaHakd+f+NJb+N+seNfbetjRWLLq3xd8KoIZ1AijLBq0phoTMB+/G5HEE="
